You will create a makefile for compiling your source code, including a clean directive.
When using g++ to compile your source code, use the -Wall switch to ensure that all
warnings are displayed. Your code should be compiled with no warnings.
